### ISSUE TITLE
Tests failing on master

### ISSUE THREAD

**Issue by sudo-suhas** [ta2edchimp/opt-cli#212] opened 2017-08-14 03:55 UTC
I was trying to fix a bug but found that 3 tests were failing on master branch:
```
λ yarn test
yarn test v0.27.5
$ ava

   12 passed
   3 failed


   1. lib » check explicit opt-ins & opt-outs (via env vars)
   retrieved opts should equal expected opts
  t.deepEqual(retrievedOpts, expectedOpts, 'retrieved opts should equal expected opts')
              |              |
              |              Object{"ENV-VAR-OPTED-IN-FOO-RULE":true,"ENV-VAR-OPTED-IN-BAR-RULE":true,"ENV-VAR-OPTED-OUT-FOO-RULE":false,"ENV-VAR-OPTED-OUT-BAR-RULE":false}
              Object{"ENV-VAR-OPTED-IN-FOO-RULE:ENV-VAR-OPTED-IN-BAR-RULE":true,"ENV-VAR-OPTED-OUT-FOO-RULE:ENV-VAR-OPTED-OUT-BAR-RULE":false}

      Test.fn (lib.js:68:5)
    _combinedTickCallback (internal/process/next_tick.js:141:11)
    process._tickCallback (internal/process/next_tick.js:180:9)


   2. lib » test for particular opt-ins (env var existing)
   ENV-VAR-OPTED-IN-FOO-RULE & ENV-VAR-OPTED-IN-BAR-RULE should be true
  t.true(testOptIn(['ENV-VAR-OPTED-IN-FOO-RULE', 'ENV-VAR-OPTED-IN-BAR-RULE']), 'ENV-VAR-OPTED-IN-FOO-RULE & ENV-VAR-OPTED-IN-BAR-RULE should be true')
         |
         false

      Test.fn (lib.js:112:3)
    _combinedTickCallback (internal/process/next_tick.js:141:11)
    process._tickCallback (internal/process/next_tick.js:180:9)


   3. lib » test for particular opt-outs (env var existing)
   ENV-VAR-OPTED-OUT-FOO-RULE & ENV-VAR-OPTED-OUT-BAR-RULE should be true
  t.true(testOptOut(['ENV-VAR-OPTED-OUT-FOO-RULE', 'ENV-VAR-OPTED-OUT-BAR-RULE']), 'ENV-VAR-OPTED-OUT-FOO-RULE & ENV-VAR-OPTED-OUT-BAR-RULE should be true')
         |
         false

      Test.fn (lib.js:174:3)
    _combinedTickCallback (internal/process/next_tick.js:141:11)
    process._tickCallback (internal/process/next_tick.js:180:9)
error Command failed with exit code 1.
```

More info:
```
λ node --version
v8.2.1

λ npm --version
5.3.0

λ yarn --version
0.27.5

λ systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.15063 N/A Build 15063
```

**Comment by ta2edchimp** [comment] 2017-10-20 08:37
Is this still reproducible for you?  
Because for me, it's not.

**Comment by sudo-suhas** [comment] 2017-10-20 12:06
Yes it is:
```
λ yarn test
yarn run v1.2.1
$ ava

  12 passed
  3 failed

  lib » check explicit opt-ins & opt-outs (via env vars)
  E:\Projects\repos\opt-cli\test\lib.js:68

   67:
   68:   t.deepEqual( retrievedOpts, expectedOpts, 'retrieved opts should equal expected opts' );
   69: } );

  retrieved opts should equal expected opts

  Difference:

    {
  -   'ENV-VAR-OPTED-IN-FOO-RULE:ENV-VAR-OPTED-IN-BAR-RULE': true,
  -   'ENV-VAR-OPTED-OUT-FOO-RULE:ENV-VAR-OPTED-OUT-BAR-RULE': false,
  +   'ENV-VAR-OPTED-IN-BAR-RULE': true,
  +   'ENV-VAR-OPTED-IN-FOO-RULE': true,
  +   'ENV-VAR-OPTED-OUT-BAR-RULE': false,
  +   'ENV-VAR-OPTED-OUT-FOO-RULE': false,
    }



  lib » test for particular opt-ins (env var existing)
  E:\Projects\repos\opt-cli\test\lib.js:112

   111:
   112:   t.true(
   113:     testOptIn( [ 'ENV-VAR-OPTED-IN-FOO-RULE', 'ENV-VAR-OPTED-IN-BAR-RULE' ] ),

  ENV-VAR-OPTED-IN-FOO-RULE & ENV-VAR-OPTED-IN-BAR-RULE should be true

  Value is not `true`:

  false

  testOptIn([ENV-VAR-OPTED-IN-FOO-RULE,ENV-VAR-OPTED-IN-BAR-RULE])
  => false

  [ENV-VAR-OPTED-IN-FOO-RULE,ENV-VAR-OPTED-IN-BAR-RULE]
  => [
    'ENV-VAR-OPTED-IN-FOO-RULE',
    'ENV-VAR-OPTED-IN-BAR-RULE',
  ]



  lib » test for particular opt-outs (env var existing)
  E:\Projects\repos\opt-cli\test\lib.js:174

   173:
   174:   t.true(
   175:     testOptOut( [ 'ENV-VAR-OPTED-OUT-FOO-RULE', 'ENV-VAR-OPTED-OUT-BAR-RULE' ] ),

  ENV-VAR-OPTED-OUT-FOO-RULE & ENV-VAR-OPTED-OUT-BAR-RULE should be true

  Value is not `true`:

  false

  testOptOut([ENV-VAR-OPTED-OUT-FOO-RULE,ENV-VAR-OPTED-OUT-BAR-RULE])
  => false

  [ENV-VAR-OPTED-OUT-FOO-RULE,ENV-VAR-OPTED-OUT-BAR-RULE]
  => [
    'ENV-VAR-OPTED-OUT-FOO-RULE',
    'ENV-VAR-OPTED-OUT-BAR-RULE',
  ]
error Command failed with exit code 1.
```

Note: I fetched in the latest master and ran `yarn` before running the tests.

**Comment by ta2edchimp** [comment] 2017-10-20 12:34
Could you please fetch `fix/windows-tests` and test again?  
I'm pretty sure it's the delimiter in the env. vars being hardcoded as ':', which is not correct for Windows machines (where it should be ';' instead).

**Comment by sudo-suhas** [comment] 2017-10-20 12:52
Yes, the failing tests are fixed in `fix/windows-tests`.

**Comment by ta2edchimp** [comment] 2017-10-20 12:55
The changed tests are merged and now available via `master`.  
Thanks for checking and reporting the issue in the first place!

**Closed as completed by ta2edchimp** 2017-10-20 12:55 UTC
